import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, FormArray } from "@angular/forms";

@Component({
  selector: 'app-inspection-dtl-form',
  templateUrl: './inspection-dtl-form.component.html',
  styleUrls: ['./inspection-dtl-form.component.scss']
})
export class InspectionDtlFormComponent implements OnInit {

  inspectiondetailsform: FormGroup;

  responseJSON = 
    {
      "1583": "1",
      "bookingid": "1610",
      "building": "Brick Veneer",
      "1337": "1",
      "drainage_comment": "",
      "1577": "1",
      "1213": "1",
      "1697": "1",
      "access_comment": "",
      "1331": "1",
      "1573": "1",
      "sewer-test": "Not tested",
      "sewer_comment": "",
      "structural_defects_comment": "",
      "height": "Two Storey",
      "inspection-finding-comment-6": "Rectify all paint defects marked to walls and ceilings to all bedrooms.",
      "inspection-finding-comment-5": "Install sealants at tile junctions and at joinery to walls.",
      "inspection-finding-comment-4": "Rectify all paint defects marked to walls and ceiling.",
      "inspection-finding-comment-3": "Install sealants at internal junctions.",
      "inspection-finding-comment-9": "Rectify all paint defects marked.",
      "inspection-finding-comment-8": "Install sealants to all wet corners and junctions.",
      "inspection-finding-comment-7": "Cracked tile at bath tap.",
      "inspection-finding-comment-2": "Replace broken pendant over island.",
      "inspection-finding-comment-1": "Rectify all paint defects marked to walls and ceilings to all rooms. ",
      "1349": "1",
      "1589": "1",
      "inspection_findings_and_recommendations-2-8": "Repair Recommended",
      "inspection_findings_and_recommendations-2-9": "Repair Recommended",
      "1103": "1",
      "1223": "1",
      "1222": "1",
      "inspection_findings_and_recommendations-2-2": "Repair Recommended",
      "inspection_findings_and_recommendations-2-3": "Repair Recommended",
      "1906": "1",
      "inspection_findings_and_recommendations-2-1": "Repair Recommended",
      "inspection_findings_and_recommendations-2-6": "Repair Recommended",
      "car_park": "Single",
      "inspection_findings_and_recommendations-2-7": "Repair Recommended",
      "1109": "1",
      "inspection_findings_and_recommendations-2-4": "Repair Recommended",
      "1229": "1",
      "inspection_findings_and_recommendations-2-5": "Repair Recommended",
      "1900": "1",
      "access": "Yes",
      "1919": "1",
      "rec-file-5": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-5",
      "1121": "1",
      "1363": "1",
      "rec-file-4": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-4",
      "1120": "1",
      "rec-file-7": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-7",
      "rec-file-6": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-6",
      "rec-file-9": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-9",
      "rec-file-8": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-8",
      "1357": "1",
      "1595": "1",
      "1913": "1",
      "1912": "1",
      "1132": "1",
      "1253": "1",
      "typee-1": "Hallways",
      "1373": "1",
      "typee-8": "Bathrooms",
      "typee-9": "Bathrooms",
      "typee-6": "Bedrooms",
      "inspection_findings_and_recommendations-1-9": "Bathrooms",
      "typee-7": "Bathrooms",
      "typee-4": "Laundry",
      "1367": "1",
      "typee-5": "Laundry",
      "typee-2": "Kitchen",
      "1001": "1",
      "typee-3": "Kitchen",
      "inspection_findings_and_recommendations-1-3": "Kitchen",
      "inspection_findings_and_recommendations-1-4": "Laundry",
      "inspection_findings_and_recommendations-1-1": "Hallways and General Living Spaces",
      "inspection_findings_and_recommendations-1-2": "Kitchen",
      "1805": "1",
      "inspection_findings_and_recommendations-1-7": "Bathrooms",
      "inspection_findings_and_recommendations-1-8": "Bathrooms",
      "inspection_findings_and_recommendations-1-5": "Laundry",
      "1009": "1",
      "inspection_findings_and_recommendations-1-6": "Bedrooms",
      "inspection-finding-comment-19": "Rectify paint to walls and ceiling \/ manhole.",
      "inspection-finding-comment-18": "Final paint entry column.",
      "inspection-finding-comment-17": "Install flexible sealants to all masonry penetrations.",
      "inspection-finding-comment-16": "Touch up dowpipes as marked.",
      "1385": "1",
      "1261": "1",
      "major_defects_comment": "",
      "1019": "1",
      "1811": "1",
      "1139": "1",
      "1930": "1",
      "1379": "1",
      "1015": "1",
      "1499": "1",
      "1135": "1",
      "piers": "Concrete",
      "inspection-finding-comment-15": "Rectify eave at vent pipe and other paint defects marked.",
      "inspection-finding-comment-14": "Attach gutter clip to front elevation.",
      "inspection-finding-comment-13": "Replace gold screws capped inside recess with stainless steel.",
      "1817": "1",
      "inspection-finding-comment-12": "Rectify flush grout to wall tiles inside recess.",
      "1937": "1",
      "inspection-finding-comment-11": "Install sealants to all wet corners and junctions.",
      "1936": "1",
      "inspection-finding-comment-10": "Replace gold screws used inside recess with stainless steel.",
      "type_2": "-",
      "type_1": "Freestanding House",
      "1151": "1",
      "1271": "1",
      "1025": "1",
      "1267": "1",
      "water_comment": "",
      "1145": "1",
      "1709": "1",
      "inspection_findings_and_recommendations-3-17": "Walls",
      "inspection_findings_and_recommendations-3-16": "Down Pipes",
      "inspection_findings_and_recommendations-3-19": "Garage\/Car Port",
      "1948": "1",
      "inspection_findings_and_recommendations-3-18": "Walls",
      "inspection_findings_and_recommendations-3-13": "Shower Screen",
      "inspection_findings_and_recommendations-3-12": "Walls",
      "1703": "1",
      "inspection_findings_and_recommendations-3-15": "Eaves",
      "1823": "1",
      "inspection_findings_and_recommendations-3-14": "Gutters",
      "smoke_detectors-test": "Not tested",
      "gas-test": "Not tested",
      "1042": "1",
      "1283": "1",
      "1954": "1",
      "1831": "1",
      "1036": "1",
      "1157": "1",
      "1277": "1",
      "gas": "Yes",
      "1717": "1",
      "1957": "1",
      "1835": "1",
      "summary": "Property present above average at completion stage with minor defects and incomplete items listed above.",
      "roof": "Metal",
      "electricity_comment": "",
      "smoke_detectors_comment": "",
      "1054": "1",
      "1175": "1",
      "drainage-test": "Not tested",
      "inspection_findings_and_recommendations-3-9": "Walls",
      "1601": "1",
      "inspection_findings_and_recommendations-3-7": "Walls",
      "1721": "1",
      "inspection_findings_and_recommendations-3-8": "Sealants",
      "1841": "1",
      "1048": "1",
      "1169": "1",
      "1289": "1",
      "inspection_findings_and_recommendations-3-1": "Walls",
      "inspection_findings_and_recommendations-3-2": "Ceiling",
      "file-01": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/file-01",
      "1607": "1",
      "inspection_findings_and_recommendations-3-5": "Sealants",
      "1727": "1",
      "inspection_findings_and_recommendations-3-6": "Walls",
      "1847": "1",
      "age": "New build",
      "inspection_findings_and_recommendations-3-3": "Sealants",
      "inspection_findings_and_recommendations-3-4": "Walls",
      "1183": "1",
      "1061": "1",
      "1613": "1",
      "1733": "1",
      "1853": "1",
      "inspection_findings_and_recommendations-2-19": "Repair Recommended",
      "weather": "Fine",
      "inspection_findings_and_recommendations-2-15": "Repair Recommended",
      "inspection_findings_and_recommendations-2-16": "Repair Recommended",
      "1619": "1",
      "inspection_findings_and_recommendations-2-17": "Repair Recommended",
      "1739": "1",
      "inspection_findings_and_recommendations-2-18": "Repair Recommended",
      "inspection_findings_and_recommendations-2-11": "Repair Recommended",
      "1859": "1",
      "inspection_findings_and_recommendations-2-12": "Repair Recommended",
      "inspection_findings_and_recommendations-2-13": "Repair Recommended",
      "inspection_findings_and_recommendations-2-14": "Repair Recommended",
      "inspection_findings_and_recommendations-2-10": "Repair Recommended",
      "1075": "1",
      "bathrooms": "Two",
      "1193": "1",
      "rec-file-13": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-13",
      "bedrooms": "Three",
      "1745": "1",
      "rec-file-14": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-14",
      "rec-file-11": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-11",
      "gas_comment": "",
      "rec-file-12": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-12",
      "rec-file-10": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-10",
      "1189": "1",
      "1067": "1",
      "rec-file-19": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-19",
      "rec-file-17": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-17",
      "rec-file-18": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-18",
      "rec-file-15": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-15",
      "1505": "1",
      "rec-file-16": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-16",
      "1625": "1",
      "1867": "1",
      "inspection_findings_and_recommendations-3-11": "Sealants",
      "inspection_findings_and_recommendations-3-10": "Shower Screen",
      "1085": "1",
      "1511": "1",
      "1751": "1",
      "sewer": "Yes",
      "1079": "1",
      "1871": "1",
      "1199": "1",
      "1519": "1",
      "major_defects": "No",
      "1757": "1",
      "1091": "1",
      "electricity": "Yes",
      "1097": "1",
      "typee-15": "External",
      "typee-16": "External",
      "1523": "1",
      "typee-13": "Ensuite",
      "1643": "1",
      "1885": "1",
      "typee-14": "External",
      "1763": "1",
      "typee-11": "Ensuite",
      "typee-12": "Ensuite",
      "1882": "1",
      "typee-10": "Bathrooms",
      "1529": "1",
      "typee-19": "External",
      "1769": "1",
      "typee-17": "External",
      "typee-18": "External",
      "structural_defects": "No",
      "1535": "1",
      "1655": "1",
      "1654": "1",
      "1894": "1",
      "water": "Yes",
      "1547": "1",
      "1667": "1",
      "1787": "1",
      "rec-file-1": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-1",
      "1301": "1",
      "1543": "1",
      "1663": "1",
      "rec-file-3": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-3",
      "rec-file-2": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/rec-file-2",
      "rec_count": "19",
      "1309": "1",
      "rep-path": "\/home\/sphillips\/IBIA_ROOT_PATH\/reports\/428\/",
      "1315": "1",
      "1678": "1",
      "1799": "1",
      "1553": "1",
      "1795": "1",
      "floor": "Slab",
      "1319": "1",
      "1559": "1",
      "1691": "1",
      "smoke_detectors": "Yes",
      "1205": "1",
      "1325": "1",
      "1687": "1",
      "1565": "1",
      "inspection_findings_and_recommendations-1-18": "External",
      "inspection_findings_and_recommendations-1-19": "External",
      "1684": "1",
      "inspection_findings_and_recommendations-1-14": "External",
      "inspection_findings_and_recommendations-1-15": "External",
      "drainage": "Yes",
      "inspection_findings_and_recommendations-1-16": "External",
      "inspection_findings_and_recommendations-1-17": "External",
      "inspection_findings_and_recommendations-1-10": "Bathrooms",
      "inspection_findings_and_recommendations-1-11": "Ensuite",
      "inspection_findings_and_recommendations-1-12": "Ensuite",
      "inspection_findings_and_recommendations-1-13": "Ensuite"
    };

  constructor() {

  }

  ngOnInit() {
    this.initForm();

    this.inspectiondetailsform.patchValue(this.responseJSON);
  }


  private initForm() {

    let hallways_recommendations = new FormArray([]);
    let kitchen_recommendations = new FormArray([]);
    let laundry_recommendations = new FormArray([]);
    let bedrooms_recommendations = new FormArray([]);
    let bathrooms_recommendations = new FormArray([]);
    let external_recommendations = new FormArray([]);
    let ensuite_recommendations = new FormArray([]);
    let timberpest_recommendations = new FormArray([]);

    //Add in a loop - todo
    hallways_recommendations.push(
      new FormGroup({
        'inspection_findings_and_recommendations-1': new FormControl(),
        'inspection_findings_and_recommendations-2': new FormControl(),
        'inspection_findings_and_recommendations-3': new FormControl(),
        'inspection-finding-comment': new FormControl()
      })
    );
    kitchen_recommendations.push(
      new FormGroup({
        'inspection_findings_and_recommendations-1': new FormControl(),
        'inspection_findings_and_recommendations-2': new FormControl(),
        'inspection_findings_and_recommendations-3': new FormControl(),
        'inspection-finding-comment': new FormControl()
      })
    );
    laundry_recommendations.push(
      new FormGroup({
        'inspection_findings_and_recommendations-1': new FormControl(),
        'inspection_findings_and_recommendations-2': new FormControl(),
        'inspection_findings_and_recommendations-3': new FormControl(),
        'inspection-finding-comment': new FormControl()
      })
    );
    bedrooms_recommendations.push(
      new FormGroup({
        'inspection_findings_and_recommendations-1': new FormControl(),
        'inspection_findings_and_recommendations-2': new FormControl(),
        'inspection_findings_and_recommendations-3': new FormControl(),
        'inspection-finding-comment': new FormControl()
      })
    );
    bathrooms_recommendations.push(
      new FormGroup({
        'inspection_findings_and_recommendations-1': new FormControl(),
        'inspection_findings_and_recommendations-2': new FormControl(),
        'inspection_findings_and_recommendations-3': new FormControl(),
        'inspection-finding-comment': new FormControl()
      })
    );
    external_recommendations.push(
      new FormGroup({
        'inspection_findings_and_recommendations-1': new FormControl(),
        'inspection_findings_and_recommendations-2': new FormControl(),
        'inspection_findings_and_recommendations-3': new FormControl(),
        'inspection-finding-comment': new FormControl()
      })
    );
    ensuite_recommendations.push(
      new FormGroup({
        'inspection_findings_and_recommendations-1': new FormControl(),
        'inspection_findings_and_recommendations-2': new FormControl(),
        'inspection_findings_and_recommendations-3': new FormControl(),
        'inspection-finding-comment': new FormControl()
      })
    );
    timberpest_recommendations.push(
      new FormGroup({
        'inspection_findings_and_recommendations-1': new FormControl(),
        'inspection_findings_and_recommendations-2': new FormControl(),
        'inspection_findings_and_recommendations-3': new FormControl(),
        'inspection-finding-comment': new FormControl()
      })
    );

    this.inspectiondetailsform = new FormGroup({
      'bookingid': new FormControl(),
      'rec_count': new FormControl(),
      'type_1': new FormControl(),
      'type_2': new FormControl(),
      'bedrooms': new FormControl(),
      'bathrooms': new FormControl(),
      'car_park': new FormControl(),
      'height': new FormControl(),
      'building': new FormControl(),
      'piers': new FormControl(),
      'floor': new FormControl(),
      'roof': new FormControl(),
      'age': new FormControl(),
      'weather': new FormControl(),
      'furnished': new FormControl(),
      'smoke': new FormControl(),
      'extension': new FormControl(),
      'extension_comment': new FormControl(),
      'electricity': new FormControl(),
      'electricity-test': new FormControl(),
      'electricity_comment': new FormControl(),
      'gas': new FormControl(),
      'gas-test': new FormControl(),
      'gas_comment': new FormControl(),
      'water': new FormControl(),
      'water-test': new FormControl(),
      'water_comment': new FormControl(),
      'sewer': new FormControl(),
      'sewer-test': new FormControl(),
      'sewer_comment': new FormControl(),
      'drainage': new FormControl(),
      'drainage-test': new FormControl(),
      'drainage_comment': new FormControl(),
      'smoke_detectors': new FormControl(),
      'smoke_detectors-test': new FormControl(),
      'smoke_detectors_comment': new FormControl(),
      'access': new FormControl(),
      'access_comment': new FormControl(),
      '1001': new FormControl(),
      '1002': new FormControl(),
      '1003': new FormControl(),
      '1004': new FormControl(),
      '1005': new FormControl(),
      '1006': new FormControl(),
      '1007': new FormControl(),
      '1008': new FormControl(),
      '1009': new FormControl(),
      '1010': new FormControl(),
      '1011': new FormControl(),
      '1012': new FormControl(),
      '1013': new FormControl(),
      '1014': new FormControl(),
      '1015': new FormControl(),
      '1016': new FormControl(),
      '1017': new FormControl(),
      '1018': new FormControl(),
      '1019': new FormControl(),
      '1020': new FormControl(),
      '1021': new FormControl(),
      '1022': new FormControl(),
      '1023': new FormControl(),
      '1024': new FormControl(),
      '1025': new FormControl(),
      '1026': new FormControl(),
      '1027': new FormControl(),
      '1028': new FormControl(),
      '1029': new FormControl(),
      '1030': new FormControl(),
      '1031': new FormControl(),
      '1032': new FormControl(),
      '1033': new FormControl(),
      '1034': new FormControl(),
      '1035': new FormControl(),
      '1036': new FormControl(),
      '1037': new FormControl(),
      '1038': new FormControl(),
      '1039': new FormControl(),
      '1040': new FormControl(),
      '1041': new FormControl(),
      '1042': new FormControl(),
      '1043': new FormControl(),
      '1044': new FormControl(),
      '1045': new FormControl(),
      '1046': new FormControl(),
      '1047': new FormControl(),
      '1048': new FormControl(),
      '1049': new FormControl(),
      '1050': new FormControl(),
      '1051': new FormControl(),
      '1052': new FormControl(),
      '1053': new FormControl(),
      '1054': new FormControl(),
      // 'inspection_findings_and_recommendations-1-<%=recCounter%>': new FormControl(),
      // 'inspection_findings_and_recommendations-2-<%=recCounter%>': new FormControl(),
      // 'inspection_findings_and_recommendations-3-<%=recCounter%>': new FormControl(),
      // 'inspection-finding-comment-<%=recCounter%>': new FormControl(),
      // 'typee-<%=recCounter++%>': new FormControl(),

      'hallways_recommendations_list': hallways_recommendations,

      '1061': new FormControl(),
      '1062': new FormControl(),
      '1063': new FormControl(),
      '1064': new FormControl(),
      '1065': new FormControl(),
      '1066': new FormControl(),
      '1067': new FormControl(),
      '1068': new FormControl(),
      '1069': new FormControl(),
      '1070': new FormControl(),
      '1071': new FormControl(),
      '1072': new FormControl(),
      '1073': new FormControl(),
      '1074': new FormControl(),
      '1075': new FormControl(),
      '1076': new FormControl(),
      '1077': new FormControl(),
      '1078': new FormControl(),
      '1079': new FormControl(),
      '1080': new FormControl(),
      '1081': new FormControl(),
      '1082': new FormControl(),
      '1083': new FormControl(),
      '1084': new FormControl(),
      '1085': new FormControl(),
      '1086': new FormControl(),
      '1087': new FormControl(),
      '1088': new FormControl(),
      '1089': new FormControl(),
      '1090': new FormControl(),
      '1091': new FormControl(),
      '1092': new FormControl(),
      '1093': new FormControl(),
      '1094': new FormControl(),
      '1095': new FormControl(),
      '1096': new FormControl(),
      '1097': new FormControl(),
      '1098': new FormControl(),
      '1099': new FormControl(),
      '1100': new FormControl(),
      '1101': new FormControl(),
      '1102': new FormControl(),
      '1103': new FormControl(),
      '1104': new FormControl(),
      '1105': new FormControl(),
      '1106': new FormControl(),
      '1107': new FormControl(),
      '1108': new FormControl(),
      '1109': new FormControl(),
      '1110': new FormControl(),
      '1111': new FormControl(),
      '1112': new FormControl(),
      '1113': new FormControl(),
      '1114': new FormControl(),
      '1115': new FormControl(),
      '1116': new FormControl(),
      '1117': new FormControl(),
      '1118': new FormControl(),
      '1119': new FormControl(),
      '1120': new FormControl(),
      '1121': new FormControl(),
      '1122': new FormControl(),
      '1123': new FormControl(),
      '1124': new FormControl(),
      '1125': new FormControl(),
      '1126': new FormControl(),
      '1127': new FormControl(),
      '1128': new FormControl(),
      '1129': new FormControl(),
      '1130': new FormControl(),
      '1131': new FormControl(),
      '1132': new FormControl(),
      '1133': new FormControl(),
      '1134': new FormControl(),
      '1135': new FormControl(),
      '1136': new FormControl(),
      '1137': new FormControl(),
      '1138': new FormControl(),
      '1139': new FormControl(),
      '1140': new FormControl(),
      '1141': new FormControl(),
      '1142': new FormControl(),
      '1143': new FormControl(),
      '1144': new FormControl(),
      '1145': new FormControl(),
      '1146': new FormControl(),
      '1147': new FormControl(),
      '1148': new FormControl(),
      '1149': new FormControl(),
      '1150': new FormControl(),
      '1151': new FormControl(),
      '1152': new FormControl(),
      '1153': new FormControl(),
      '1154': new FormControl(),
      '1155': new FormControl(),
      '1156': new FormControl(),
      '1157': new FormControl(),
      '1158': new FormControl(),
      '1159': new FormControl(),
      '1160': new FormControl(),
      '1161': new FormControl(),
      '1162': new FormControl(),
      // 'inspection_findings_and_recommendations-1-<%=recCounter%>': new FormControl(),
      // 'inspection_findings_and_recommendations-2-<%=recCounter%>': new FormControl(),
      // 'inspection_findings_and_recommendations-3-<%=recCounter%>': new FormControl(),
      // 'inspection-finding-comment-<%=recCounter%>': new FormControl(),
      // 'rec-file-<%=recCounter%>': new FormControl(),
      // 'typee-<%=recCounter++%>': new FormControl(),

      'kitchen_recommendations_list': kitchen_recommendations,  

      '1169': new FormControl(),
      '1170': new FormControl(),
      '1171': new FormControl(),
      '1172': new FormControl(),
      '1173': new FormControl(),
      '1174': new FormControl(),
      '1175': new FormControl(),
      '1176': new FormControl(),
      '1177': new FormControl(),
      '1178': new FormControl(),
      '1179': new FormControl(),
      '1180': new FormControl(),
      '1181': new FormControl(),
      '1182': new FormControl(),
      '1183': new FormControl(),
      '1184': new FormControl(),
      '1185': new FormControl(),
      '1186': new FormControl(),
      '1187': new FormControl(),
      '1188': new FormControl(),
      '1189': new FormControl(),
      '1190': new FormControl(),
      '1191': new FormControl(),
      '1192': new FormControl(),
      '1193': new FormControl(),
      '1194': new FormControl(),
      '1195': new FormControl(),
      '1196': new FormControl(),
      '1197': new FormControl(),
      '1198': new FormControl(),
      '1199': new FormControl(),
      '1200': new FormControl(),
      '1201': new FormControl(),
      '1202': new FormControl(),
      '1203': new FormControl(),
      '1204': new FormControl(),
      '1205': new FormControl(),
      '1206': new FormControl(),
      '1207': new FormControl(),
      '1208': new FormControl(),
      '1209': new FormControl(),
      '1210': new FormControl(),
      '1211': new FormControl(),
      '1212': new FormControl(),
      '1213': new FormControl(),
      '1214': new FormControl(),
      '1215': new FormControl(),
      '1216': new FormControl(),
      '1217': new FormControl(),
      '1218': new FormControl(),
      '1219': new FormControl(),
      '1220': new FormControl(),
      '1221': new FormControl(),
      '1222': new FormControl(),
      '1223': new FormControl(),
      '1224': new FormControl(),
      '1225': new FormControl(),
      '1226': new FormControl(),
      '1227': new FormControl(),
      '1228': new FormControl(),
      '1229': new FormControl(),
      '1230': new FormControl(),
      '1231': new FormControl(),
      '1232': new FormControl(),
      '1233': new FormControl(),
      '1234': new FormControl(),
      // 'inspection_findings_and_recommendations-1-<%=recCounter%>': new FormControl(),
      // 'inspection_findings_and_recommendations-2-<%=recCounter%>': new FormControl(),
      // 'inspection_findings_and_recommendations-3-<%=recCounter%>': new FormControl(),
      // 'inspection-finding-comment-<%=recCounter%>': new FormControl(),
      // 'typee-<%=recCounter++%>': new FormControl(),

      'laundry_recommendations_list': laundry_recommendations,

      '1253': new FormControl(),
      '1254': new FormControl(),
      '1255': new FormControl(),
      '1256': new FormControl(),
      '1257': new FormControl(),
      '1258': new FormControl(),
      '1259': new FormControl(),
      '1260': new FormControl(),
      '1261': new FormControl(),
      '1262': new FormControl(),
      '1263': new FormControl(),
      '1264': new FormControl(),
      '1265': new FormControl(),
      '1266': new FormControl(),
      '1267': new FormControl(),
      '1268': new FormControl(),
      '1269': new FormControl(),
      '1270': new FormControl(),
      '1271': new FormControl(),
      '1272': new FormControl(),
      '1273': new FormControl(),
      '1274': new FormControl(),
      '1275': new FormControl(),
      '1276': new FormControl(),
      '1277': new FormControl(),
      '1278': new FormControl(),
      '1279': new FormControl(),
      '1280': new FormControl(),
      '1281': new FormControl(),
      '1282': new FormControl(),
      '1283': new FormControl(),
      '1284': new FormControl(),
      '1285': new FormControl(),
      '1286': new FormControl(),
      '1287': new FormControl(),
      '1288': new FormControl(),
      '1289': new FormControl(),
      '1290': new FormControl(),
      '1291': new FormControl(),
      '1292': new FormControl(),
      '1293': new FormControl(),
      '1294': new FormControl(),
      '1301': new FormControl(),
      '1302': new FormControl(),
      '1303': new FormControl(),
      '1304': new FormControl(),
      '1305': new FormControl(),
      '1306': new FormControl(),
      '1307': new FormControl(),
      '1308': new FormControl(),
      '1309': new FormControl(),
      '1310': new FormControl(),
      '1311': new FormControl(),
      '1312': new FormControl(),
      '1313': new FormControl(),
      '1314': new FormControl(),
      '1315': new FormControl(),
      '1316': new FormControl(),
      '1317': new FormControl(),
      '1318': new FormControl(),
      '1319': new FormControl(),
      '1320': new FormControl(),
      '1321': new FormControl(),
      '1322': new FormControl(),
      '1323': new FormControl(),
      '1324': new FormControl(),
      '1325': new FormControl(),
      '1326': new FormControl(),
      '1327': new FormControl(),
      '1328': new FormControl(),
      '1329': new FormControl(),
      '1330': new FormControl(),
      '1331': new FormControl(),
      '1332': new FormControl(),
      '1333': new FormControl(),
      '1334': new FormControl(),
      '1335': new FormControl(),
      '1336': new FormControl(),
      '1337': new FormControl(),
      '1338': new FormControl(),
      '1339': new FormControl(),
      '1340': new FormControl(),
      '1341': new FormControl(),
      '1342': new FormControl(),
      '1349': new FormControl(),
      '1350': new FormControl(),
      '1351': new FormControl(),
      '1352': new FormControl(),
      '1353': new FormControl(),
      '1354': new FormControl(),
      '1355': new FormControl(),
      '1356': new FormControl(),
      '1357': new FormControl(),
      '1358': new FormControl(),
      '1359': new FormControl(),
      '1360': new FormControl(),
      '1361': new FormControl(),
      '1362': new FormControl(),
      '1363': new FormControl(),
      '1364': new FormControl(),
      '1365': new FormControl(),
      '1366': new FormControl(),
      '1367': new FormControl(),
      '1368': new FormControl(),
      '1369': new FormControl(),
      '1370': new FormControl(),
      '1371': new FormControl(),
      '1372': new FormControl(),
      '1373': new FormControl(),
      '1374': new FormControl(),
      '1375': new FormControl(),
      '1376': new FormControl(),
      '1377': new FormControl(),
      '1378': new FormControl(),
      '1379': new FormControl(),
      '1380': new FormControl(),
      '1381': new FormControl(),
      '1382': new FormControl(),
      '1383': new FormControl(),
      '1384': new FormControl(),
      '1385': new FormControl(),
      '1386': new FormControl(),
      '1387': new FormControl(),
      '1388': new FormControl(),
      '1389': new FormControl(),
      '1390': new FormControl(),
      '1397': new FormControl(),
      '1398': new FormControl(),
      '1399': new FormControl(),
      '1400': new FormControl(),
      '1401': new FormControl(),
      '1402': new FormControl(),
      '1403': new FormControl(),
      '1404': new FormControl(),
      '1405': new FormControl(),
      '1406': new FormControl(),
      '1407': new FormControl(),
      '1408': new FormControl(),
      '1409': new FormControl(),
      '1410': new FormControl(),
      '1411': new FormControl(),
      '1412': new FormControl(),
      '1413': new FormControl(),
      '1414': new FormControl(),
      '1415': new FormControl(),
      '1416': new FormControl(),
      '1417': new FormControl(),
      '1418': new FormControl(),
      '1419': new FormControl(),
      '1420': new FormControl(),
      '1421': new FormControl(),
      '1422': new FormControl(),
      '1423': new FormControl(),
      '1424': new FormControl(),
      '1425': new FormControl(),
      '1426': new FormControl(),
      '1427': new FormControl(),
      '1428': new FormControl(),
      '1429': new FormControl(),
      '1430': new FormControl(),
      '1431': new FormControl(),
      '1432': new FormControl(),
      '1433': new FormControl(),
      '1434': new FormControl(),
      '1435': new FormControl(),
      '1436': new FormControl(),
      '1437': new FormControl(),
      '1438': new FormControl(),
      '1445': new FormControl(),
      '1446': new FormControl(),
      '1447': new FormControl(),
      '1448': new FormControl(),
      '1449': new FormControl(),
      '1450': new FormControl(),
      '1451': new FormControl(),
      '1452': new FormControl(),
      '1453': new FormControl(),
      '1454': new FormControl(),
      '1455': new FormControl(),
      '1456': new FormControl(),
      '1457': new FormControl(),
      '1458': new FormControl(),
      '1459': new FormControl(),
      '1460': new FormControl(),
      '1461': new FormControl(),
      '1462': new FormControl(),
      '1463': new FormControl(),
      '1464': new FormControl(),
      '1465': new FormControl(),
      '1466': new FormControl(),
      '1467': new FormControl(),
      '1468': new FormControl(),
      '1469': new FormControl(),
      '1470': new FormControl(),
      '1471': new FormControl(),
      '1472': new FormControl(),
      '1473': new FormControl(),
      '1474': new FormControl(),
      '1475': new FormControl(),
      '1476': new FormControl(),
      '1477': new FormControl(),
      '1478': new FormControl(),
      '1479': new FormControl(),
      '1480': new FormControl(),
      '1481': new FormControl(),
      '1482': new FormControl(),
      '1483': new FormControl(),
      '1484': new FormControl(),
      '1485': new FormControl(),
      '1486': new FormControl(),
      // 'inspection_findings_and_recommendations-1-<%=recCounter%>': new FormControl(),
      // 'inspection_findings_and_recommendations-2-<%=recCounter%>': new FormControl(),
      // 'inspection_findings_and_recommendations-3-<%=recCounter%>': new FormControl(),
      // 'inspection-finding-comment-<%=recCounter%>': new FormControl(),
      // 'typee-<%=recCounter++%>': new FormControl(),

      'bedrooms_recommendations_list': bedrooms_recommendations,

      '1499': new FormControl(),
      '1500': new FormControl(),
      '1501': new FormControl(),
      '1502': new FormControl(),
      '1503': new FormControl(),
      '1504': new FormControl(),
      '1505': new FormControl(),
      '1506': new FormControl(),
      '1507': new FormControl(),
      '1508': new FormControl(),
      '1509': new FormControl(),
      '1510': new FormControl(),
      '1511': new FormControl(),
      '1512': new FormControl(),
      '1513': new FormControl(),
      '1514': new FormControl(),
      '1515': new FormControl(),
      '1516': new FormControl(),
      '1517': new FormControl(),
      '1518': new FormControl(),
      '1519': new FormControl(),
      '1520': new FormControl(),
      '1521': new FormControl(),
      '1522': new FormControl(),
      '1523': new FormControl(),
      '1524': new FormControl(),
      '1525': new FormControl(),
      '1526': new FormControl(),
      '1527': new FormControl(),
      '1528': new FormControl(),
      '1529': new FormControl(),
      '1530': new FormControl(),
      '1531': new FormControl(),
      '1532': new FormControl(),
      '1533': new FormControl(),
      '1534': new FormControl(),
      '1535': new FormControl(),
      '1536': new FormControl(),
      '1537': new FormControl(),
      '1538': new FormControl(),
      '1539': new FormControl(),
      '1540': new FormControl(),
      '1541': new FormControl(),
      '1542': new FormControl(),
      '1543': new FormControl(),
      '1544': new FormControl(),
      '1545': new FormControl(),
      '1546': new FormControl(),
      '1547': new FormControl(),
      '1548': new FormControl(),
      '1549': new FormControl(),
      '1550': new FormControl(),
      '1551': new FormControl(),
      '1552': new FormControl(),
      '1553': new FormControl(),
      '1554': new FormControl(),
      '1555': new FormControl(),
      '1556': new FormControl(),
      '1557': new FormControl(),
      '1558': new FormControl(),
      '1559': new FormControl(),
      '1560': new FormControl(),
      '1561': new FormControl(),
      '1562': new FormControl(),
      '1563': new FormControl(),
      '1564': new FormControl(),
      '1565': new FormControl(),
      '1566': new FormControl(),
      '1567': new FormControl(),
      '1568': new FormControl(),
      '1569': new FormControl(),
      '1570': new FormControl(),
      '1571': new FormControl(),
      '1572': new FormControl(),
      '1573': new FormControl(),
      '1574': new FormControl(),
      '1575': new FormControl(),
      '1576': new FormControl(),
      '1577': new FormControl(),
      '1578': new FormControl(),
      '1579': new FormControl(),
      '1580': new FormControl(),
      '1581': new FormControl(),
      '1582': new FormControl(),
      '1583': new FormControl(),
      '1584': new FormControl(),
      '1585': new FormControl(),
      '1586': new FormControl(),
      '1587': new FormControl(),
      '1588': new FormControl(),
      '1589': new FormControl(),
      '1590': new FormControl(),
      '1591': new FormControl(),
      '1592': new FormControl(),
      '1593': new FormControl(),
      '1594': new FormControl(),
      '1595': new FormControl(),
      '1596': new FormControl(),
      '1597': new FormControl(),
      '1598': new FormControl(),
      '1599': new FormControl(),
      '1600': new FormControl(),
      '1601': new FormControl(),
      '1602': new FormControl(),
      '1603': new FormControl(),
      '1604': new FormControl(),
      '1605': new FormControl(),
      '1606': new FormControl(),
      '1607': new FormControl(),
      '1608': new FormControl(),
      '1609': new FormControl(),
      '1610': new FormControl(),
      '1611': new FormControl(),
      '1612': new FormControl(),
      '1613': new FormControl(),
      '1614': new FormControl(),
      '1615': new FormControl(),
      '1616': new FormControl(),
      '1617': new FormControl(),
      '1618': new FormControl(),
      '1619': new FormControl(),
      '1620': new FormControl(),
      '1621': new FormControl(),
      '1622': new FormControl(),
      '1623': new FormControl(),
      '1624': new FormControl(),
      '1625': new FormControl(),
      '1626': new FormControl(),
      '1627': new FormControl(),
      '1628': new FormControl(),
      '1629': new FormControl(),
      '1630': new FormControl(),
      // 'inspection_findings_and_recommendations-1-<%=recCounter%>': new FormControl(),
      // 'inspection_findings_and_recommendations-2-<%=recCounter%>': new FormControl(),
      // 'inspection_findings_and_recommendations-3-<%=recCounter%>': new FormControl(),
      // 'inspection-finding-comment-<%=recCounter%>': new FormControl(),
      // 'typee-<%=recCounter++%>': new FormControl(),

      'bathrooms_recommendations_list': bathrooms_recommendations,

      '1643': new FormControl(),
      '1644': new FormControl(),
      '1645': new FormControl(),
      '1646': new FormControl(),
      '1647': new FormControl(),
      '1648': new FormControl(),
      '1649': new FormControl(),
      '1650': new FormControl(),
      '1651': new FormControl(),
      '1652': new FormControl(),
      '1653': new FormControl(),
      '1654': new FormControl(),
      '1655': new FormControl(),
      '1656': new FormControl(),
      '1657': new FormControl(),
      '1658': new FormControl(),
      '1659': new FormControl(),
      '1660': new FormControl(),
      '1661': new FormControl(),
      '1662': new FormControl(),
      '1663': new FormControl(),
      '1664': new FormControl(),
      '1665': new FormControl(),
      '1666': new FormControl(),
      '1667': new FormControl(),
      '1668': new FormControl(),
      '1669': new FormControl(),
      '1670': new FormControl(),
      '1671': new FormControl(),
      '1672': new FormControl(),
      '1673': new FormControl(),
      '1674': new FormControl(),
      '1675': new FormControl(),
      '1676': new FormControl(),
      '1677': new FormControl(),
      '1678': new FormControl(),
      '1679': new FormControl(),
      '1680': new FormControl(),
      '1681': new FormControl(),
      '1682': new FormControl(),
      '1683': new FormControl(),
      '1684': new FormControl(),
      '1685': new FormControl(),
      '1686': new FormControl(),
      '1687': new FormControl(),
      '1688': new FormControl(),
      '1689': new FormControl(),
      '1690': new FormControl(),
      '1691': new FormControl(),
      '1692': new FormControl(),
      '1693': new FormControl(),
      '1694': new FormControl(),
      '1695': new FormControl(),
      '1696': new FormControl(),
      '1697': new FormControl(),
      '1698': new FormControl(),
      '1699': new FormControl(),
      '1700': new FormControl(),
      '1701': new FormControl(),
      '1702': new FormControl(),
      '1703': new FormControl(),
      '1704': new FormControl(),
      '1705': new FormControl(),
      '1706': new FormControl(),
      '1707': new FormControl(),
      '1708': new FormControl(),
      '1709': new FormControl(),
      '1710': new FormControl(),
      '1711': new FormControl(),
      '1712': new FormControl(),
      '1713': new FormControl(),
      '1714': new FormControl(),
      '1715': new FormControl(),
      '1716': new FormControl(),
      '1717': new FormControl(),
      '1718': new FormControl(),
      '1719': new FormControl(),
      '1720': new FormControl(),
      '1721': new FormControl(),
      '1722': new FormControl(),
      '1723': new FormControl(),
      '1724': new FormControl(),
      '1725': new FormControl(),
      '1726': new FormControl(),
      '1727': new FormControl(),
      '1728': new FormControl(),
      '1729': new FormControl(),
      '1730': new FormControl(),
      '1731': new FormControl(),
      '1732': new FormControl(),
      '1733': new FormControl(),
      '1734': new FormControl(),
      '1735': new FormControl(),
      '1736': new FormControl(),
      '1737': new FormControl(),
      '1738': new FormControl(),
      '1739': new FormControl(),
      '1740': new FormControl(),
      '1741': new FormControl(),
      '1742': new FormControl(),
      '1743': new FormControl(),
      '1744': new FormControl(),
      '1745': new FormControl(),
      '1746': new FormControl(),
      '1747': new FormControl(),
      '1748': new FormControl(),
      '1749': new FormControl(),
      '1750': new FormControl(),
      '1751': new FormControl(),
      '1752': new FormControl(),
      '1753': new FormControl(),
      '1754': new FormControl(),
      '1755': new FormControl(),
      '1756': new FormControl(),
      '1757': new FormControl(),
      '1758': new FormControl(),
      '1759': new FormControl(),
      '1760': new FormControl(),
      '1761': new FormControl(),
      '1762': new FormControl(),
      '1763': new FormControl(),
      '1764': new FormControl(),
      '1765': new FormControl(),
      '1766': new FormControl(),
      '1767': new FormControl(),
      '1768': new FormControl(),
      '1769': new FormControl(),
      '1770': new FormControl(),
      '1771': new FormControl(),
      '1772': new FormControl(),
      '1773': new FormControl(),
      '1774': new FormControl(),
      // 'inspection_findings_and_recommendations-1-<%=recCounter%>': new FormControl(),
      // 'inspection_findings_and_recommendations-2-<%=recCounter%>': new FormControl(),
      // 'inspection_findings_and_recommendations-3-<%=recCounter%>': new FormControl(),
      // 'inspection-finding-comment-<%=recCounter%>': new FormControl(),
      // 'typee-<%=recCounter++%>': new FormControl(),

      'ensuite_recommendations_list': ensuite_recommendations,

      '1787': new FormControl(),
      '1788': new FormControl(),
      '1789': new FormControl(),
      '1790': new FormControl(),
      '1791': new FormControl(),
      '1792': new FormControl(),
      '1793': new FormControl(),
      '1794': new FormControl(),
      '1795': new FormControl(),
      '1796': new FormControl(),
      '1797': new FormControl(),
      '1798': new FormControl(),
      '1799': new FormControl(),
      '1800': new FormControl(),
      '1801': new FormControl(),
      '1802': new FormControl(),
      '1803': new FormControl(),
      '1804': new FormControl(),
      '1805': new FormControl(),
      '1806': new FormControl(),
      '1807': new FormControl(),
      '1808': new FormControl(),
      '1809': new FormControl(),
      '1810': new FormControl(),
      '1811': new FormControl(),
      '1812': new FormControl(),
      '1813': new FormControl(),
      '1814': new FormControl(),
      '1815': new FormControl(),
      '1816': new FormControl(),
      '1817': new FormControl(),
      '1818': new FormControl(),
      '1819': new FormControl(),
      '1820': new FormControl(),
      '1821': new FormControl(),
      '1822': new FormControl(),
      '1823': new FormControl(),
      '1824': new FormControl(),
      '1825': new FormControl(),
      '1826': new FormControl(),
      '1827': new FormControl(),
      '1828': new FormControl(),
      '1829': new FormControl(),
      '1830': new FormControl(),
      '1831': new FormControl(),
      '1832': new FormControl(),
      '1833': new FormControl(),
      '1834': new FormControl(),
      '1835': new FormControl(),
      '1836': new FormControl(),
      '1837': new FormControl(),
      '1838': new FormControl(),
      '1839': new FormControl(),
      '1840': new FormControl(),
      '1841': new FormControl(),
      '1842': new FormControl(),
      '1843': new FormControl(),
      '1844': new FormControl(),
      '1845': new FormControl(),
      '1846': new FormControl(),
      '1847': new FormControl(),
      '1848': new FormControl(),
      '1849': new FormControl(),
      '1850': new FormControl(),
      '1851': new FormControl(),
      '1852': new FormControl(),
      '1853': new FormControl(),
      '1854': new FormControl(),
      '1855': new FormControl(),
      '1856': new FormControl(),
      '1857': new FormControl(),
      '1858': new FormControl(),
      '1859': new FormControl(),
      '1860': new FormControl(),
      '1861': new FormControl(),
      '1862': new FormControl(),
      '1863': new FormControl(),
      '1864': new FormControl(),
      '1865': new FormControl(),
      '1866': new FormControl(),
      '1867': new FormControl(),
      '1868': new FormControl(),
      '1869': new FormControl(),
      '1870': new FormControl(),
      '1871': new FormControl(),
      '1872': new FormControl(),
      '1873': new FormControl(),
      '1874': new FormControl(),
      '1875': new FormControl(),
      '1876': new FormControl(),
      '1877': new FormControl(),
      '1878': new FormControl(),
      '1879': new FormControl(),
      '1880': new FormControl(),
      '1881': new FormControl(),
      '1882': new FormControl(),
      '1883': new FormControl(),
      '1884': new FormControl(),
      '1885': new FormControl(),
      '1886': new FormControl(),
      '1887': new FormControl(),
      '1888': new FormControl(),
      '1889': new FormControl(),
      '1890': new FormControl(),
      '1891': new FormControl(),
      '1892': new FormControl(),
      '1893': new FormControl(),
      '1894': new FormControl(),
      '1895': new FormControl(),
      '1896': new FormControl(),
      '1897': new FormControl(),
      '1898': new FormControl(),
      '1899': new FormControl(),
      '1900': new FormControl(),
      '1901': new FormControl(),
      '1902': new FormControl(),
      '1903': new FormControl(),
      '1904': new FormControl(),
      '1905': new FormControl(),
      '1906': new FormControl(),
      '1907': new FormControl(),
      '1908': new FormControl(),
      '1909': new FormControl(),
      '1910': new FormControl(),
      '1911': new FormControl(),
      '1912': new FormControl(),
      '1913': new FormControl(),
      '1914': new FormControl(),
      '1915': new FormControl(),
      '1916': new FormControl(),
      '1917': new FormControl(),
      '1918': new FormControl(),
      '1919': new FormControl(),
      '1920': new FormControl(),
      '1921': new FormControl(),
      '1922': new FormControl(),
      '1923': new FormControl(),
      '1924': new FormControl(),
      '1925': new FormControl(),
      '1926': new FormControl(),
      '1927': new FormControl(),
      '1928': new FormControl(),
      '1929': new FormControl(),
      '1930': new FormControl(),
      '1931': new FormControl(),
      '1932': new FormControl(),
      '1933': new FormControl(),
      '1934': new FormControl(),
      '1935': new FormControl(),
      '1936': new FormControl(),
      '1937': new FormControl(),
      '1938': new FormControl(),
      '1939': new FormControl(),
      '1940': new FormControl(),
      '1941': new FormControl(),
      '1942': new FormControl(),
      '1943': new FormControl(),
      '1944': new FormControl(),
      '1945': new FormControl(),
      '1946': new FormControl(),
      '1947': new FormControl(),
      '1948': new FormControl(),
      '1949': new FormControl(),
      '1950': new FormControl(),
      '1951': new FormControl(),
      '1952': new FormControl(),
      '1953': new FormControl(),
      '1954': new FormControl(),
      '1955': new FormControl(),
      '1956': new FormControl(),
      '1957': new FormControl(),
      '1958': new FormControl(),
      '1959': new FormControl(),
      '1960': new FormControl(),
      // 'inspection_findings_and_recommendations-1-<%=recCounter%>': new FormControl(),
      // 'inspection_findings_and_recommendations-2-<%=recCounter%>': new FormControl(),
      // 'inspection_findings_and_recommendations-3-<%=recCounter%>': new FormControl(),
      // 'inspection-finding-comment-<%=recCounter%>': new FormControl(),
      // 'typee-<%=recCounter++%>': new FormControl(),

      'external_recommendations_list': external_recommendations,


      'summary': new FormControl(),
      'major_defects': new FormControl(),
      'major_defects_comment': new FormControl(),
      'structural_defects': new FormControl(),
      'structural_defects_comment': new FormControl(),
      '1985': new FormControl(),
      '1986': new FormControl(),
      '1987': new FormControl(),
      '1988': new FormControl(),
      '1989': new FormControl(),
      '1990': new FormControl(),
      '1991': new FormControl(),
      '1992': new FormControl(),
      '2000': new FormControl(),
      '2001': new FormControl(),
      '2002': new FormControl(),
      '2003': new FormControl(),
      '2004': new FormControl(),
      '2005': new FormControl(),
      '2006': new FormControl(),
      '2007': new FormControl(),
      '2008': new FormControl(),
      '2009': new FormControl(),
      '2010': new FormControl(),
      '2011': new FormControl(),
      '2012': new FormControl(),
      '2013': new FormControl(),
      '2014': new FormControl(),
      '2015': new FormControl(),
      '2016': new FormControl(),
      '2017': new FormControl(),
      '2018': new FormControl(),
      '2019': new FormControl(),
      '2020': new FormControl(),
      '2021': new FormControl(),
      '2022': new FormControl(),
      '2023': new FormControl(),
      '2024': new FormControl(),
      '2025': new FormControl(),
      '2026': new FormControl(),
      '2027': new FormControl(),
      '2028': new FormControl(),
      '2029': new FormControl(),
      '2030': new FormControl(),
      '2031': new FormControl(),
      '2032': new FormControl(),
      '2033': new FormControl(),
      '2034': new FormControl(),
      '2035': new FormControl(),
      '2036': new FormControl(),
      '2037': new FormControl(),
      '2038': new FormControl(),
      '2039': new FormControl(),
      '2040': new FormControl(),
      '2041': new FormControl(),
      '2042': new FormControl(),
      '2043': new FormControl(),
      '2044': new FormControl(),
      '2045': new FormControl(),
      '2046': new FormControl(),
      '2047': new FormControl(),
      '2048': new FormControl(),
      '2049': new FormControl(),
      '2050': new FormControl(),
      '2051': new FormControl(),
      '2052': new FormControl(),
      '2053': new FormControl(),
      '2054': new FormControl(),
      '2055': new FormControl(),
      '2056': new FormControl(),
      '2057': new FormControl(),
      '2058': new FormControl(),
      '2059': new FormControl(),
      '2060': new FormControl(),
      '2061': new FormControl(),
      '2062': new FormControl(),
      '2063': new FormControl(),
      '2064': new FormControl(),
      '2065': new FormControl(),
      '2066': new FormControl(),
      '2067': new FormControl(),
      '2068': new FormControl(),
      '2069': new FormControl(),
      '2070': new FormControl(),
      '2071': new FormControl(),
      '2072': new FormControl(),
      '2073': new FormControl(),
      '2074': new FormControl(),
      '2075': new FormControl(),
      '2076': new FormControl(),
      '2077': new FormControl(),
      '2078': new FormControl(),
      '2079': new FormControl(),
      '2080': new FormControl(),
      '2081': new FormControl(),
      '2082': new FormControl(),
      '2083': new FormControl(),
      // 'inspection_findings_and_recommendations-1-<%=recCounter%>': new FormControl(),
      // 'inspection_findings_and_recommendations-2-<%=recCounter%>': new FormControl(),
      // 'inspection_findings_and_recommendations-3-<%=recCounter%>': new FormControl(),
      // 'inspection-finding-comment-<%=recCounter%>': new FormControl(),
      // 'typee-<%=recCounter++%>': new FormControl(),

      'timberpest_recommendations_list': timberpest_recommendations,

      '2096': new FormControl(),
      '2097': new FormControl(),
      '2098': new FormControl(),
      '2099': new FormControl(),
      '2100': new FormControl(),
      'Areas_Conducive_note': new FormControl(),
      '2103': new FormControl(),
      '2104': new FormControl(),
      '2105': new FormControl(),
      'Report_on_Drainage_note': new FormControl(),
      '2108': new FormControl(),
      '2109': new FormControl(),
      '2110': new FormControl(),
      'Report_on_Ventilation_note': new FormControl(),
      '2113': new FormControl(),
      '2114': new FormControl(),
      '2115': new FormControl(),
      'Evidence_note': new FormControl(),
      '2120': new FormControl(),
      '2121': new FormControl(),
      '2122': new FormControl(),
      '2123': new FormControl(),
      '2124': new FormControl(),
      '2125': new FormControl(),
      'timber_summary': new FormControl()
    });
  }



}

/**
 * 
 * this.inspectiondetailsform = new FormGroup({
      'bookingid': new FormControl(),
      'rec_count': new FormControl(),
      'type_1': new FormControl(),
      'type_2': new FormControl(),
      'bedrooms': new FormControl(),
      'bathrooms': new FormControl(),
      'car_park': new FormControl(),
      'height': new FormControl(),
      'building': new FormControl(),
      'piers': new FormControl(),
      'floor': new FormControl(),
      'roof': new FormControl(),
      'age': new FormControl(),
      'weather': new FormControl(),
      'furnished': new FormControl(),
      'smoke': new FormControl(),
      'extension': new FormControl(),
      'extension_comment': new FormControl(),
      'electricity': new FormControl(),
      'electricity-test': new FormControl(),
      'electricity_comment': new FormControl(),
      'gas': new FormControl(),
      'gas-test': new FormControl(),
      'gas_comment': new FormControl(),
      'water': new FormControl(),
      'water-test': new FormControl(),
      'water_comment': new FormControl(),
      'sewer': new FormControl(),
      'sewer-test': new FormControl(),
      'sewer_comment': new FormControl(),
      'drainage': new FormControl(),
      'drainage-test': new FormControl(),
      'drainage_comment': new FormControl(),
      'smoke_detectors': new FormControl(),
      'smoke_detectors-test': new FormControl(),
      'smoke_detectors_comment': new FormControl(),
      'access': new FormControl(),
      'access_comment': new FormControl(),
      '1001': new FormControl(),
      '1002': new FormControl(),
      '1003': new FormControl(),
      '1004': new FormControl(),
      '1005': new FormControl(),
      '1006': new FormControl(),
      '1007': new FormControl(),
      '1008': new FormControl(),
      '1009': new FormControl(),
      '1010': new FormControl(),
      '1011': new FormControl(),
      '1012': new FormControl(),
      '1013': new FormControl(),
      '1014': new FormControl(),
      '1015': new FormControl(),
      '1016': new FormControl(),
      '1017': new FormControl(),
      '1018': new FormControl(),
      '1019': new FormControl(),
      '1020': new FormControl(),
      '1021': new FormControl(),
      '1022': new FormControl(),
      '1023': new FormControl(),
      '1024': new FormControl(),
      '1025': new FormControl(),
      '1026': new FormControl(),
      '1027': new FormControl(),
      '1028': new FormControl(),
      '1029': new FormControl(),
      '1030': new FormControl(),
      '1031': new FormControl(),
      '1032': new FormControl(),
      '1033': new FormControl(),
      '1034': new FormControl(),
      '1035': new FormControl(),
      '1036': new FormControl(),
      '1037': new FormControl(),
      '1038': new FormControl(),
      '1039': new FormControl(),
      '1040': new FormControl(),
      '1041': new FormControl(),
      '1042': new FormControl(),
      '1043': new FormControl(),
      '1044': new FormControl(),
      '1045': new FormControl(),
      '1046': new FormControl(),
      '1047': new FormControl(),
      '1048': new FormControl(),
      '1049': new FormControl(),
      '1050': new FormControl(),
      '1051': new FormControl(),
      '1052': new FormControl(),
      '1053': new FormControl(),
      '1054': new FormControl(),
      'inspection_findings_and_recommendations-1-<%=recCounter%>': new FormControl(),
      'inspection_findings_and_recommendations-2-<%=recCounter%>': new FormControl(),
      'inspection_findings_and_recommendations-3-<%=recCounter%>': new FormControl(),
      'inspection-finding-comment-<%=recCounter%>': new FormControl(),
      'typee-<%=recCounter++%>': new FormControl(),
      '1061': new FormControl(),
      '1062': new FormControl(),
      '1063': new FormControl(),
      '1064': new FormControl(),
      '1065': new FormControl(),
      '1066': new FormControl(),
      '1067': new FormControl(),
      '1068': new FormControl(),
      '1069': new FormControl(),
      '1070': new FormControl(),
      '1071': new FormControl(),
      '1072': new FormControl(),
      '1073': new FormControl(),
      '1074': new FormControl(),
      '1075': new FormControl(),
      '1076': new FormControl(),
      '1077': new FormControl(),
      '1078': new FormControl(),
      '1079': new FormControl(),
      '1080': new FormControl(),
      '1081': new FormControl(),
      '1082': new FormControl(),
      '1083': new FormControl(),
      '1084': new FormControl(),
      '1085': new FormControl(),
      '1086': new FormControl(),
      '1087': new FormControl(),
      '1088': new FormControl(),
      '1089': new FormControl(),
      '1090': new FormControl(),
      '1091': new FormControl(),
      '1092': new FormControl(),
      '1093': new FormControl(),
      '1094': new FormControl(),
      '1095': new FormControl(),
      '1096': new FormControl(),
      '1097': new FormControl(),
      '1098': new FormControl(),
      '1099': new FormControl(),
      '1100': new FormControl(),
      '1101': new FormControl(),
      '1102': new FormControl(),
      '1103': new FormControl(),
      '1104': new FormControl(),
      '1105': new FormControl(),
      '1106': new FormControl(),
      '1107': new FormControl(),
      '1108': new FormControl(),
      '1109': new FormControl(),
      '1110': new FormControl(),
      '1111': new FormControl(),
      '1112': new FormControl(),
      '1113': new FormControl(),
      '1114': new FormControl(),
      '1115': new FormControl(),
      '1116': new FormControl(),
      '1117': new FormControl(),
      '1118': new FormControl(),
      '1119': new FormControl(),
      '1120': new FormControl(),
      '1121': new FormControl(),
      '1122': new FormControl(),
      '1123': new FormControl(),
      '1124': new FormControl(),
      '1125': new FormControl(),
      '1126': new FormControl(),
      '1127': new FormControl(),
      '1128': new FormControl(),
      '1129': new FormControl(),
      '1130': new FormControl(),
      '1131': new FormControl(),
      '1132': new FormControl(),
      '1133': new FormControl(),
      '1134': new FormControl(),
      '1135': new FormControl(),
      '1136': new FormControl(),
      '1137': new FormControl(),
      '1138': new FormControl(),
      '1139': new FormControl(),
      '1140': new FormControl(),
      '1141': new FormControl(),
      '1142': new FormControl(),
      '1143': new FormControl(),
      '1144': new FormControl(),
      '1145': new FormControl(),
      '1146': new FormControl(),
      '1147': new FormControl(),
      '1148': new FormControl(),
      '1149': new FormControl(),
      '1150': new FormControl(),
      '1151': new FormControl(),
      '1152': new FormControl(),
      '1153': new FormControl(),
      '1154': new FormControl(),
      '1155': new FormControl(),
      '1156': new FormControl(),
      '1157': new FormControl(),
      '1158': new FormControl(),
      '1159': new FormControl(),
      '1160': new FormControl(),
      '1161': new FormControl(),
      '1162': new FormControl(),
      'inspection_findings_and_recommendations-1-<%=recCounter%>': new FormControl(),
      'inspection_findings_and_recommendations-2-<%=recCounter%>': new FormControl(),
      'inspection_findings_and_recommendations-3-<%=recCounter%>': new FormControl(),
      'inspection-finding-comment-<%=recCounter%>': new FormControl(),
      'rec-file-<%=recCounter%>': new FormControl(),
      'typee-<%=recCounter++%>': new FormControl(),
      '1169': new FormControl(),
      '1170': new FormControl(),
      '1171': new FormControl(),
      '1172': new FormControl(),
      '1173': new FormControl(),
      '1174': new FormControl(),
      '1175': new FormControl(),
      '1176': new FormControl(),
      '1177': new FormControl(),
      '1178': new FormControl(),
      '1179': new FormControl(),
      '1180': new FormControl(),
      '1181': new FormControl(),
      '1182': new FormControl(),
      '1183': new FormControl(),
      '1184': new FormControl(),
      '1185': new FormControl(),
      '1186': new FormControl(),
      '1187': new FormControl(),
      '1188': new FormControl(),
      '1189': new FormControl(),
      '1190': new FormControl(),
      '1191': new FormControl(),
      '1192': new FormControl(),
      '1193': new FormControl(),
      '1194': new FormControl(),
      '1195': new FormControl(),
      '1196': new FormControl(),
      '1197': new FormControl(),
      '1198': new FormControl(),
      '1199': new FormControl(),
      '1200': new FormControl(),
      '1201': new FormControl(),
      '1202': new FormControl(),
      '1203': new FormControl(),
      '1204': new FormControl(),
      '1205': new FormControl(),
      '1206': new FormControl(),
      '1207': new FormControl(),
      '1208': new FormControl(),
      '1209': new FormControl(),
      '1210': new FormControl(),
      '1211': new FormControl(),
      '1212': new FormControl(),
      '1213': new FormControl(),
      '1214': new FormControl(),
      '1215': new FormControl(),
      '1216': new FormControl(),
      '1217': new FormControl(),
      '1218': new FormControl(),
      '1219': new FormControl(),
      '1220': new FormControl(),
      '1221': new FormControl(),
      '1222': new FormControl(),
      '1223': new FormControl(),
      '1224': new FormControl(),
      '1225': new FormControl(),
      '1226': new FormControl(),
      '1227': new FormControl(),
      '1228': new FormControl(),
      '1229': new FormControl(),
      '1230': new FormControl(),
      '1231': new FormControl(),
      '1232': new FormControl(),
      '1233': new FormControl(),
      '1234': new FormControl(),
      'inspection_findings_and_recommendations-1-<%=recCounter%>': new FormControl(),
      'inspection_findings_and_recommendations-2-<%=recCounter%>': new FormControl(),
      'inspection_findings_and_recommendations-3-<%=recCounter%>': new FormControl(),
      'inspection-finding-comment-<%=recCounter%>': new FormControl(),
      'typee-<%=recCounter++%>': new FormControl(),
      '1253': new FormControl(),
      '1254': new FormControl(),
      '1255': new FormControl(),
      '1256': new FormControl(),
      '1257': new FormControl(),
      '1258': new FormControl(),
      '1259': new FormControl(),
      '1260': new FormControl(),
      '1261': new FormControl(),
      '1262': new FormControl(),
      '1263': new FormControl(),
      '1264': new FormControl(),
      '1265': new FormControl(),
      '1266': new FormControl(),
      '1267': new FormControl(),
      '1268': new FormControl(),
      '1269': new FormControl(),
      '1270': new FormControl(),
      '1271': new FormControl(),
      '1272': new FormControl(),
      '1273': new FormControl(),
      '1274': new FormControl(),
      '1275': new FormControl(),
      '1276': new FormControl(),
      '1277': new FormControl(),
      '1278': new FormControl(),
      '1279': new FormControl(),
      '1280': new FormControl(),
      '1281': new FormControl(),
      '1282': new FormControl(),
      '1283': new FormControl(),
      '1284': new FormControl(),
      '1285': new FormControl(),
      '1286': new FormControl(),
      '1287': new FormControl(),
      '1288': new FormControl(),
      '1289': new FormControl(),
      '1290': new FormControl(),
      '1291': new FormControl(),
      '1292': new FormControl(),
      '1293': new FormControl(),
      '1294': new FormControl(),
      '1301': new FormControl(),
      '1302': new FormControl(),
      '1303': new FormControl(),
      '1304': new FormControl(),
      '1305': new FormControl(),
      '1306': new FormControl(),
      '1307': new FormControl(),
      '1308': new FormControl(),
      '1309': new FormControl(),
      '1310': new FormControl(),
      '1311': new FormControl(),
      '1312': new FormControl(),
      '1313': new FormControl(),
      '1314': new FormControl(),
      '1315': new FormControl(),
      '1316': new FormControl(),
      '1317': new FormControl(),
      '1318': new FormControl(),
      '1319': new FormControl(),
      '1320': new FormControl(),
      '1321': new FormControl(),
      '1322': new FormControl(),
      '1323': new FormControl(),
      '1324': new FormControl(),
      '1325': new FormControl(),
      '1326': new FormControl(),
      '1327': new FormControl(),
      '1328': new FormControl(),
      '1329': new FormControl(),
      '1330': new FormControl(),
      '1331': new FormControl(),
      '1332': new FormControl(),
      '1333': new FormControl(),
      '1334': new FormControl(),
      '1335': new FormControl(),
      '1336': new FormControl(),
      '1337': new FormControl(),
      '1338': new FormControl(),
      '1339': new FormControl(),
      '1340': new FormControl(),
      '1341': new FormControl(),
      '1342': new FormControl(),
      '1349': new FormControl(),
      '1350': new FormControl(),
      '1351': new FormControl(),
      '1352': new FormControl(),
      '1353': new FormControl(),
      '1354': new FormControl(),
      '1355': new FormControl(),
      '1356': new FormControl(),
      '1357': new FormControl(),
      '1358': new FormControl(),
      '1359': new FormControl(),
      '1360': new FormControl(),
      '1361': new FormControl(),
      '1362': new FormControl(),
      '1363': new FormControl(),
      '1364': new FormControl(),
      '1365': new FormControl(),
      '1366': new FormControl(),
      '1367': new FormControl(),
      '1368': new FormControl(),
      '1369': new FormControl(),
      '1370': new FormControl(),
      '1371': new FormControl(),
      '1372': new FormControl(),
      '1373': new FormControl(),
      '1374': new FormControl(),
      '1375': new FormControl(),
      '1376': new FormControl(),
      '1377': new FormControl(),
      '1378': new FormControl(),
      '1379': new FormControl(),
      '1380': new FormControl(),
      '1381': new FormControl(),
      '1382': new FormControl(),
      '1383': new FormControl(),
      '1384': new FormControl(),
      '1385': new FormControl(),
      '1386': new FormControl(),
      '1387': new FormControl(),
      '1388': new FormControl(),
      '1389': new FormControl(),
      '1390': new FormControl(),
      '1397': new FormControl(),
      '1398': new FormControl(),
      '1399': new FormControl(),
      '1400': new FormControl(),
      '1401': new FormControl(),
      '1402': new FormControl(),
      '1403': new FormControl(),
      '1404': new FormControl(),
      '1405': new FormControl(),
      '1406': new FormControl(),
      '1407': new FormControl(),
      '1408': new FormControl(),
      '1409': new FormControl(),
      '1410': new FormControl(),
      '1411': new FormControl(),
      '1412': new FormControl(),
      '1413': new FormControl(),
      '1414': new FormControl(),
      '1415': new FormControl(),
      '1416': new FormControl(),
      '1417': new FormControl(),
      '1418': new FormControl(),
      '1419': new FormControl(),
      '1420': new FormControl(),
      '1421': new FormControl(),
      '1422': new FormControl(),
      '1423': new FormControl(),
      '1424': new FormControl(),
      '1425': new FormControl(),
      '1426': new FormControl(),
      '1427': new FormControl(),
      '1428': new FormControl(),
      '1429': new FormControl(),
      '1430': new FormControl(),
      '1431': new FormControl(),
      '1432': new FormControl(),
      '1433': new FormControl(),
      '1434': new FormControl(),
      '1435': new FormControl(),
      '1436': new FormControl(),
      '1437': new FormControl(),
      '1438': new FormControl(),
      '1445': new FormControl(),
      '1446': new FormControl(),
      '1447': new FormControl(),
      '1448': new FormControl(),
      '1449': new FormControl(),
      '1450': new FormControl(),
      '1451': new FormControl(),
      '1452': new FormControl(),
      '1453': new FormControl(),
      '1454': new FormControl(),
      '1455': new FormControl(),
      '1456': new FormControl(),
      '1457': new FormControl(),
      '1458': new FormControl(),
      '1459': new FormControl(),
      '1460': new FormControl(),
      '1461': new FormControl(),
      '1462': new FormControl(),
      '1463': new FormControl(),
      '1464': new FormControl(),
      '1465': new FormControl(),
      '1466': new FormControl(),
      '1467': new FormControl(),
      '1468': new FormControl(),
      '1469': new FormControl(),
      '1470': new FormControl(),
      '1471': new FormControl(),
      '1472': new FormControl(),
      '1473': new FormControl(),
      '1474': new FormControl(),
      '1475': new FormControl(),
      '1476': new FormControl(),
      '1477': new FormControl(),
      '1478': new FormControl(),
      '1479': new FormControl(),
      '1480': new FormControl(),
      '1481': new FormControl(),
      '1482': new FormControl(),
      '1483': new FormControl(),
      '1484': new FormControl(),
      '1485': new FormControl(),
      '1486': new FormControl(),
      'inspection_findings_and_recommendations-1-<%=recCounter%>': new FormControl(),
      'inspection_findings_and_recommendations-2-<%=recCounter%>': new FormControl(),
      'inspection_findings_and_recommendations-3-<%=recCounter%>': new FormControl(),
      'inspection-finding-comment-<%=recCounter%>': new FormControl(),
      'typee-<%=recCounter++%>': new FormControl(),
      '1499': new FormControl(),
      '1500': new FormControl(),
      '1501': new FormControl(),
      '1502': new FormControl(),
      '1503': new FormControl(),
      '1504': new FormControl(),
      '1505': new FormControl(),
      '1506': new FormControl(),
      '1507': new FormControl(),
      '1508': new FormControl(),
      '1509': new FormControl(),
      '1510': new FormControl(),
      '1511': new FormControl(),
      '1512': new FormControl(),
      '1513': new FormControl(),
      '1514': new FormControl(),
      '1515': new FormControl(),
      '1516': new FormControl(),
      '1517': new FormControl(),
      '1518': new FormControl(),
      '1519': new FormControl(),
      '1520': new FormControl(),
      '1521': new FormControl(),
      '1522': new FormControl(),
      '1523': new FormControl(),
      '1524': new FormControl(),
      '1525': new FormControl(),
      '1526': new FormControl(),
      '1527': new FormControl(),
      '1528': new FormControl(),
      '1529': new FormControl(),
      '1530': new FormControl(),
      '1531': new FormControl(),
      '1532': new FormControl(),
      '1533': new FormControl(),
      '1534': new FormControl(),
      '1535': new FormControl(),
      '1536': new FormControl(),
      '1537': new FormControl(),
      '1538': new FormControl(),
      '1539': new FormControl(),
      '1540': new FormControl(),
      '1541': new FormControl(),
      '1542': new FormControl(),
      '1543': new FormControl(),
      '1544': new FormControl(),
      '1545': new FormControl(),
      '1546': new FormControl(),
      '1547': new FormControl(),
      '1548': new FormControl(),
      '1549': new FormControl(),
      '1550': new FormControl(),
      '1551': new FormControl(),
      '1552': new FormControl(),
      '1553': new FormControl(),
      '1554': new FormControl(),
      '1555': new FormControl(),
      '1556': new FormControl(),
      '1557': new FormControl(),
      '1558': new FormControl(),
      '1559': new FormControl(),
      '1560': new FormControl(),
      '1561': new FormControl(),
      '1562': new FormControl(),
      '1563': new FormControl(),
      '1564': new FormControl(),
      '1565': new FormControl(),
      '1566': new FormControl(),
      '1567': new FormControl(),
      '1568': new FormControl(),
      '1569': new FormControl(),
      '1570': new FormControl(),
      '1571': new FormControl(),
      '1572': new FormControl(),
      '1573': new FormControl(),
      '1574': new FormControl(),
      '1575': new FormControl(),
      '1576': new FormControl(),
      '1577': new FormControl(),
      '1578': new FormControl(),
      '1579': new FormControl(),
      '1580': new FormControl(),
      '1581': new FormControl(),
      '1582': new FormControl(),
      '1583': new FormControl(),
      '1584': new FormControl(),
      '1585': new FormControl(),
      '1586': new FormControl(),
      '1587': new FormControl(),
      '1588': new FormControl(),
      '1589': new FormControl(),
      '1590': new FormControl(),
      '1591': new FormControl(),
      '1592': new FormControl(),
      '1593': new FormControl(),
      '1594': new FormControl(),
      '1595': new FormControl(),
      '1596': new FormControl(),
      '1597': new FormControl(),
      '1598': new FormControl(),
      '1599': new FormControl(),
      '1600': new FormControl(),
      '1601': new FormControl(),
      '1602': new FormControl(),
      '1603': new FormControl(),
      '1604': new FormControl(),
      '1605': new FormControl(),
      '1606': new FormControl(),
      '1607': new FormControl(),
      '1608': new FormControl(),
      '1609': new FormControl(),
      '1610': new FormControl(),
      '1611': new FormControl(),
      '1612': new FormControl(),
      '1613': new FormControl(),
      '1614': new FormControl(),
      '1615': new FormControl(),
      '1616': new FormControl(),
      '1617': new FormControl(),
      '1618': new FormControl(),
      '1619': new FormControl(),
      '1620': new FormControl(),
      '1621': new FormControl(),
      '1622': new FormControl(),
      '1623': new FormControl(),
      '1624': new FormControl(),
      '1625': new FormControl(),
      '1626': new FormControl(),
      '1627': new FormControl(),
      '1628': new FormControl(),
      '1629': new FormControl(),
      '1630': new FormControl(),
      'inspection_findings_and_recommendations-1-<%=recCounter%>': new FormControl(),
      'inspection_findings_and_recommendations-2-<%=recCounter%>': new FormControl(),
      'inspection_findings_and_recommendations-3-<%=recCounter%>': new FormControl(),
      'inspection-finding-comment-<%=recCounter%>': new FormControl(),
      'typee-<%=recCounter++%>': new FormControl(),
      '1643': new FormControl(),
      '1644': new FormControl(),
      '1645': new FormControl(),
      '1646': new FormControl(),
      '1647': new FormControl(),
      '1648': new FormControl(),
      '1649': new FormControl(),
      '1650': new FormControl(),
      '1651': new FormControl(),
      '1652': new FormControl(),
      '1653': new FormControl(),
      '1654': new FormControl(),
      '1655': new FormControl(),
      '1656': new FormControl(),
      '1657': new FormControl(),
      '1658': new FormControl(),
      '1659': new FormControl(),
      '1660': new FormControl(),
      '1661': new FormControl(),
      '1662': new FormControl(),
      '1663': new FormControl(),
      '1664': new FormControl(),
      '1665': new FormControl(),
      '1666': new FormControl(),
      '1667': new FormControl(),
      '1668': new FormControl(),
      '1669': new FormControl(),
      '1670': new FormControl(),
      '1671': new FormControl(),
      '1672': new FormControl(),
      '1673': new FormControl(),
      '1674': new FormControl(),
      '1675': new FormControl(),
      '1676': new FormControl(),
      '1677': new FormControl(),
      '1678': new FormControl(),
      '1679': new FormControl(),
      '1680': new FormControl(),
      '1681': new FormControl(),
      '1682': new FormControl(),
      '1683': new FormControl(),
      '1684': new FormControl(),
      '1685': new FormControl(),
      '1686': new FormControl(),
      '1687': new FormControl(),
      '1688': new FormControl(),
      '1689': new FormControl(),
      '1690': new FormControl(),
      '1691': new FormControl(),
      '1692': new FormControl(),
      '1693': new FormControl(),
      '1694': new FormControl(),
      '1695': new FormControl(),
      '1696': new FormControl(),
      '1697': new FormControl(),
      '1698': new FormControl(),
      '1699': new FormControl(),
      '1700': new FormControl(),
      '1701': new FormControl(),
      '1702': new FormControl(),
      '1703': new FormControl(),
      '1704': new FormControl(),
      '1705': new FormControl(),
      '1706': new FormControl(),
      '1707': new FormControl(),
      '1708': new FormControl(),
      '1709': new FormControl(),
      '1710': new FormControl(),
      '1711': new FormControl(),
      '1712': new FormControl(),
      '1713': new FormControl(),
      '1714': new FormControl(),

      '1715': new FormControl(),
      '1716': new FormControl(),
      '1717': new FormControl(),
      '1718': new FormControl(),
      '1719': new FormControl(),
      '1720': new FormControl(),
      '1721': new FormControl(),
      '1722': new FormControl(),
      '1723': new FormControl(),
      '1724': new FormControl(),
      '1725': new FormControl(),
      '1726': new FormControl(),
      '1727': new FormControl(),
      '1728': new FormControl(),
      '1729': new FormControl(),
      '1730': new FormControl(),
      '1731': new FormControl(),
      '1732': new FormControl(),
      '1733': new FormControl(),
      '1734': new FormControl(),
      '1735': new FormControl(),
      '1736': new FormControl(),
      '1737': new FormControl(),
      '1738': new FormControl(),
      '1739': new FormControl(),
      '1740': new FormControl(),
      '1741': new FormControl(),
      '1742': new FormControl(),
      '1743': new FormControl(),
      '1744': new FormControl(),
      '1745': new FormControl(),
      '1746': new FormControl(),
      '1747': new FormControl(),
      '1748': new FormControl(),
      '1749': new FormControl(),
      '1750': new FormControl(),
      '1751': new FormControl(),
      '1752': new FormControl(),
      '1753': new FormControl(),
      '1754': new FormControl(),
      '1755': new FormControl(),
      '1756': new FormControl(),
      '1757': new FormControl(),
      '1758': new FormControl(),
      '1759': new FormControl(),
      '1760': new FormControl(),
      '1761': new FormControl(),
      '1762': new FormControl(),
      '1763': new FormControl(),
      '1764': new FormControl(),
      '1765': new FormControl(),
      '1766': new FormControl(),
      '1767': new FormControl(),
      '1768': new FormControl(),
      '1769': new FormControl(),
      '1770': new FormControl(),
      '1771': new FormControl(),
      '1772': new FormControl(),
      '1773': new FormControl(),
      '1774': new FormControl(),
      'inspection_findings_and_recommendations-1-<%=recCounter%>': new FormControl(),
      'inspection_findings_and_recommendations-2-<%=recCounter%>': new FormControl(),
      'inspection_findings_and_recommendations-3-<%=recCounter%>': new FormControl(),
      'inspection-finding-comment-<%=recCounter%>': new FormControl(),
      'typee-<%=recCounter++%>': new FormControl(),
      '1787': new FormControl(),
      '1788': new FormControl(),
      '1789': new FormControl(),
      '1790': new FormControl(),
      '1791': new FormControl(),
      '1792': new FormControl(),
      '1793': new FormControl(),
      '1794': new FormControl(),
      '1795': new FormControl(),
      '1796': new FormControl(),
      '1797': new FormControl(),
      '1798': new FormControl(),
      '1799': new FormControl(),
      '1800': new FormControl(),
      '1801': new FormControl(),
      '1802': new FormControl(),
      '1803': new FormControl(),
      '1804': new FormControl(),
      '1805': new FormControl(),
      '1806': new FormControl(),
      '1807': new FormControl(),
      '1808': new FormControl(),
      '1809': new FormControl(),
      '1810': new FormControl(),
      '1811': new FormControl(),
      '1812': new FormControl(),
      '1813': new FormControl(),
      '1814': new FormControl(),
      '1815': new FormControl(),
      '1816': new FormControl(),
      '1817': new FormControl(),
      '1818': new FormControl(),
      '1819': new FormControl(),
      '1820': new FormControl(),
      '1821': new FormControl(),
      '1822': new FormControl(),
      '1823': new FormControl(),
      '1824': new FormControl(),
      '1825': new FormControl(),
      '1826': new FormControl(),
      '1827': new FormControl(),
      '1828': new FormControl(),
      '1829': new FormControl(),
      '1830': new FormControl(),
      '1831': new FormControl(),
      '1832': new FormControl(),
      '1833': new FormControl(),
      '1834': new FormControl(),
      '1835': new FormControl(),
      '1836': new FormControl(),
      '1837': new FormControl(),
      '1838': new FormControl(),
      '1839': new FormControl(),
      '1840': new FormControl(),
      '1841': new FormControl(),
      '1842': new FormControl(),
      '1843': new FormControl(),
      '1844': new FormControl(),
      '1845': new FormControl(),
      '1846': new FormControl(),
      '1847': new FormControl(),
      '1848': new FormControl(),
      '1849': new FormControl(),
      '1850': new FormControl(),
      '1851': new FormControl(),
      '1852': new FormControl(),
      '1853': new FormControl(),
      '1854': new FormControl(),
      '1855': new FormControl(),
      '1856': new FormControl(),
      '1857': new FormControl(),
      '1858': new FormControl(),
      '1859': new FormControl(),
      '1860': new FormControl(),
      '1861': new FormControl(),
      '1862': new FormControl(),
      '1863': new FormControl(),
      '1864': new FormControl(),
      '1865': new FormControl(),
      '1866': new FormControl(),
      '1867': new FormControl(),
      '1868': new FormControl(),
      '1869': new FormControl(),
      '1870': new FormControl(),
      '1871': new FormControl(),
      '1872': new FormControl(),
      '1873': new FormControl(),
      '1874': new FormControl(),
      '1875': new FormControl(),
      '1876': new FormControl(),
      '1877': new FormControl(),
      '1878': new FormControl(),
      '1879': new FormControl(),
      '1880': new FormControl(),
      '1881': new FormControl(),
      '1882': new FormControl(),
      '1883': new FormControl(),
      '1884': new FormControl(),
      '1885': new FormControl(),
      '1886': new FormControl(),
      '1887': new FormControl(),
      '1888': new FormControl(),
      '1889': new FormControl(),
      '1890': new FormControl(),
      '1891': new FormControl(),
      '1892': new FormControl(),
      '1893': new FormControl(),
      '1894': new FormControl(),
      '1895': new FormControl(),
      '1896': new FormControl(),
      '1897': new FormControl(),
      '1898': new FormControl(),
      '1899': new FormControl(),
      '1900': new FormControl(),
      '1901': new FormControl(),
      '1902': new FormControl(),
      '1903': new FormControl(),
      '1904': new FormControl(),
      '1905': new FormControl(),
      '1906': new FormControl(),
      '1907': new FormControl(),
      '1908': new FormControl(),
      '1909': new FormControl(),
      '1910': new FormControl(),
      '1911': new FormControl(),
      '1912': new FormControl(),
      '1913': new FormControl(),
      '1914': new FormControl(),
      '1915': new FormControl(),
      '1916': new FormControl(),
      '1917': new FormControl(),
      '1918': new FormControl(),
      '1919': new FormControl(),
      '1920': new FormControl(),
      '1921': new FormControl(),
      '1922': new FormControl(),
      '1923': new FormControl(),
      '1924': new FormControl(),
      '1925': new FormControl(),
      '1926': new FormControl(),
      '1927': new FormControl(),
      '1928': new FormControl(),
      '1929': new FormControl(),
      '1930': new FormControl(),
      '1931': new FormControl(),
      '1932': new FormControl(),
      '1933': new FormControl(),
      '1934': new FormControl(),
      '1935': new FormControl(),
      '1936': new FormControl(),
      '1937': new FormControl(),
      '1938': new FormControl(),
      '1939': new FormControl(),
      '1940': new FormControl(),
      '1941': new FormControl(),
      '1942': new FormControl(),
      '1943': new FormControl(),
      '1944': new FormControl(),
      '1945': new FormControl(),
      '1946': new FormControl(),
      '1947': new FormControl(),
      '1948': new FormControl(),
      '1949': new FormControl(),
      '1950': new FormControl(),
      '1951': new FormControl(),
      '1952': new FormControl(),
      '1953': new FormControl(),
      '1954': new FormControl(),
      '1955': new FormControl(),
      '1956': new FormControl(),
      '1957': new FormControl(),
      '1958': new FormControl(),
      '1959': new FormControl(),
      '1960': new FormControl(),
      'inspection_findings_and_recommendations-1-<%=recCounter%>': new FormControl(),
      'inspection_findings_and_recommendations-2-<%=recCounter%>': new FormControl(),
      'inspection_findings_and_recommendations-3-<%=recCounter%>': new FormControl(),
      'inspection-finding-comment-<%=recCounter%>': new FormControl(),
      'typee-<%=recCounter++%>': new FormControl(),
      'summary': new FormControl(),
      'major_defects': new FormControl(),
      'major_defects': new FormControl(),
      'major_defects_comment': new FormControl(),
      'structural_defects': new FormControl(),
      'structural_defects': new FormControl(),
      'structural_defects_comment': new FormControl(),
      '1985': new FormControl(),
      '1986': new FormControl(),
      '1987': new FormControl(),
      '1988': new FormControl(),
      '1989': new FormControl(),
      '1990': new FormControl(),
      '1991': new FormControl(),
      '1992': new FormControl(),
      '2000': new FormControl(),
      '2001': new FormControl(),
      '2002': new FormControl(),
      '2003': new FormControl(),
      '2004': new FormControl(),
      '2005': new FormControl(),
      '2006': new FormControl(),
      '2007': new FormControl(),
      '2008': new FormControl(),
      '2009': new FormControl(),
      '2010': new FormControl(),
      '2011': new FormControl(),
      '2012': new FormControl(),
      '2013': new FormControl(),
      '2014': new FormControl(),
      '2015': new FormControl(),
      '2016': new FormControl(),
      '2017': new FormControl(),
      '2018': new FormControl(),
      '2019': new FormControl(),
      '2020': new FormControl(),
      '2021': new FormControl(),
      '2022': new FormControl(),
      '2023': new FormControl(),
      '2024': new FormControl(),
      '2025': new FormControl(),
      '2026': new FormControl(),
      '2027': new FormControl(),
      '2028': new FormControl(),
      '2029': new FormControl(),
      '2030': new FormControl(),
      '2031': new FormControl(),
      '2032': new FormControl(),
      '2033': new FormControl(),
      '2034': new FormControl(),
      '2035': new FormControl(),
      '2036': new FormControl(),
      '2037': new FormControl(),
      '2038': new FormControl(),
      '2039': new FormControl(),
      '2040': new FormControl(),
      '2041': new FormControl(),
      '2042': new FormControl(),
      '2043': new FormControl(),
      '2044': new FormControl(),
      '2045': new FormControl(),
      '2046': new FormControl(),
      '2047': new FormControl(),
      '2048': new FormControl(),
      '2049': new FormControl(),
      '2050': new FormControl(),
      '2051': new FormControl(),
      '2052': new FormControl(),
      '2053': new FormControl(),
      '2054': new FormControl(),
      '2055': new FormControl(),
      '2056': new FormControl(),
      '2057': new FormControl(),
      '2058': new FormControl(),
      '2059': new FormControl(),
      '2060': new FormControl(),
      '2061': new FormControl(),
      '2062': new FormControl(),
      '2063': new FormControl(),
      '2064': new FormControl(),
      '2065': new FormControl(),
      '2066': new FormControl(),
      '2067': new FormControl(),
      '2068': new FormControl(),
      '2069': new FormControl(),
      '2070': new FormControl(),
      '2071': new FormControl(),
      '2072': new FormControl(),
      '2073': new FormControl(),
      '2074': new FormControl(),
      '2075': new FormControl(),
      '2076': new FormControl(),
      '2077': new FormControl(),
      '2078': new FormControl(),
      '2079': new FormControl(),
      '2080': new FormControl(),
      '2081': new FormControl(),
      '2082': new FormControl(),
      '2083': new FormControl(),
      'inspection_findings_and_recommendations-1-<%=recCounter%>': new FormControl(),
      'inspection_findings_and_recommendations-2-<%=recCounter%>': new FormControl(),
      'inspection_findings_and_recommendations-3-<%=recCounter%>': new FormControl(),
      'inspection-finding-comment-<%=recCounter%>': new FormControl(),
      'typee-<%=recCounter++%>': new FormControl(),
      '2096': new FormControl(),
      '2097': new FormControl(),
      '2098': new FormControl(),
      '2099': new FormControl(),
      '2100': new FormControl(),
      'Areas_Conducive_note': new FormControl(),
      '2103': new FormControl(),
      '2104': new FormControl(),
      '2105': new FormControl(),
      'Report_on_Drainage_note': new FormControl(),
      '2108': new FormControl(),
      '2109': new FormControl(),
      '2110': new FormControl(),
      'Report_on_Ventilation_note': new FormControl(),
      '2113': new FormControl(),
      '2114': new FormControl(),
      '2115': new FormControl(),
      'Evidence_note': new FormControl(),
      '2120': new FormControl(),
      '2121': new FormControl(),
      '2122': new FormControl(),
      '2123': new FormControl(),
      '2124': new FormControl(),
      '2125': new FormControl(),
      'timber_summary': new FormControl()
    })
 */